### PR TITLE
Use vue demi to support Vue2 and Vue3

### PR DESCRIPTION
**Pull request by sduduzog**
## What kind of change does this PR introduce?
Chore: A conditional check for a VueJS version. This attempts to use https://github.com/vueuse/vue-demi  as mentioned in https://github.com/supabase/vue-supabase/pull/2

## What is the current behavior?
Package only supports use in VueJS V2

## What is the new behavior?
- Includes support for Vue3
- Exposes `useSupabase` possible through the `provide/inject` api
- For Vue 2.x users will have to also install @vue/composition-api

## Additional context
This has been manually tested against a Vue 2.x, Vue 3.x (with vue cli and vite) and a nuxt project with a `nuxt-supabase` fork

### CODE REVIEW

**Comment by sduduzog** [comment]
Finally comfortable with this PR @scottrobertson 

I also updated the README with the changes in usage

**Comment by scottrobertson** [comment]
Thanks @sduduzog.

I am guessing there is no way around having to use `@vue/composition-api`?

@NuroDev do you have any suggestions around that?

**Comment by NuroDev** [comment]
Nope, all looks good to me 👍🏻

**Comment by scottrobertson** [comment]
> Nope, all looks good to me 👍🏻

Thank you. 

@sduduzog have you done any integration testing already for Nuxt-Supabase yet or should I do that?

**Comment by sduduzog** [comment]
@scottrobertson I have, in a private repo. All works well, still with the composition-api being a prerequisite.

**Comment by sduduzog** [comment]
I still recommend you test too, I'll create a PR for nuxt-supabase with this branch

**Pull request merged**
